sonar.projectKey=melessmb_fraud_guard
sonar.organization=melessmb

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/dist/**,\
  **/__pycache__/**,\
  **/migrations/**,\
  **/infrastructure/**,\
  frontend/src/components/ui/**

sonar.python.version=3.13
sonar.javascript.environments=browser,node

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
